### ISSUE TITLE
[Question] Use UnaryServerInterceptor with otel.tracer

### ISSUE THREAD

**Issue by jumpyBiggins** [open-telemetry/opentelemetry-go-contrib#563]
I was an older version of otel(v0.11) and I was using the tracer in a UnaryServerInterceptor. 
after the update to v0.16.0

the below code does not work because tracer does not implement the `Apply` method
```
tracer := otel.Tracer("testTracer")
opts := grpc.ChainUnaryInterceptor(otelgrpc.UnaryServerInterceptor(tracer))
```

what is the workaround for this? 

thanks.

**Comment by MrAlias** [comment]
The `UnaryServerInterceptor` is created by passing `otelgrpc.Options` to the function:

https://github.com/open-telemetry/opentelemetry-go-contrib/blob/90490eca4f9dd4e1f5a47d69b010a1f958c8b43f/instrumentation/google.golang.org/grpc/otelgrpc/interceptor.go#L302-L304

An `otel.Tracer` is no longer passed to the tracer as the instrumentation manages its' own `Tracer` as the OTel project is designed to work: the instrumentation should create a representative Tracer to create spans with. Removing that argument to `otelgrpc.UnaryServerInterceptor` should resolve this.
